### ISSUE TITLE
Networking- Extended

### ISSUE THREAD

**Issue by iayanpahwa** [linuxchixin/talks#17]
**Abstract**

Linux Extended Networking:

In the last meet-up, we had some amazing talks on networking, I'll be picking up from there and talking about few more networking protocols.

**About**

* Secure Shell or SSH
* Telnet
* File Transfer Protocol(FTP and sFTP)
* Message Queue Telemetry and Transport Protocol(MQTT)
* Serial Communication protocol and UART
* Netcat: Networking swiss army knife

**Pre-requisites**
* Basic CLI exposure

**Expected duration**
20 mins

**Level**
Begineers

**Resources**

[LinuxNetworking](http://linux-training.be/linuxnet.pdf)

**Speaker Bio**

Just a tech...
https://iayanpahwa.github.io/about/

**Comment by cocoa1231** [comment]
Hi! Would you be able to give this talk on the 24th?

**Comment by iayanpahwa** [comment]
Hi @cocoa1231 I'll be mostly traveling this and next week so don't think would be able to prepare or even make it to the next meetup.
