### ISSUE TITLE
Building Your First Linux Kernel

### ISSUE THREAD

**Issue by HimanshiJain** [linuxchixin/talks#2]
This talk would involve the following:
1. versions of Linux Kernel
2. Basic git
3. Downloading (Prerequisite)
4. making Config file 
5. Build components and file structure
6. Compiling, Building (considerable time if to be done on the spot)
7. Running

**Comment by nihilist-banana** [comment]
Hi, are you available for delivering this talk in the meetup on 12th May?

**Comment by shivan1b** [comment]
@nihilist-banana oops this is a closed issue. This talk has already been delivered.
