### ISSUE TITLE
NPM install and chill

### ISSUE THREAD

**Issue by PrabhanshuAttri** [linuxchixin/talks#22]
**Abstract**
This will be a talk about Nodejs and the world’s largest software registry, NPM, the package manager for JavaScript.

**About**

JavaScript’s rising popularity has brought with it a lot of changes, and the face of web development today is dramatically different. The things that we can do on the web nowadays with JavaScript running on the server, as well as in the browser, were hard to imagine just several years ago or were encapsulated within sandboxed environments like Flash or Java Applets. This talk is about how to deploy a server side application for APIs with nodejs and npm.

**Pre-requisites**

- Should have a basic understanding of JavaScript, API and websites

**Expected duration**

25-30mins

**Level**

Beginner

**Resources**

[Getting Started](https://blog.risingstack.com/node-hero-tutorial-getting-started-with-node-js/)

**Speaker Bio**

[Prabhanshu Attri](http://www.prabhanshu.com/about/)

**Comment by rajudev** [comment]
I am part of a team who packages npm packages into Debian. May be we can have a workshop or small talk regarding 'Debian Packaging of Javascript Modules' followed by a talk of yours.

**Comment by CuriousLearner** [comment]
@shivan1b Please update the talks in `README` once you tag them as completed :)
