### ISSUE TITLE
Meilix & Meilix generator 

### ISSUE THREAD

**Issue by xeon-zolt** [linuxchixin/talks#24]
**Abstract**

 I want to talk about the project I am working on Meilix and Meilix generator 
Meilix is the only LXQT based distro in the market and Meilix Generator is a web app to generate custom Meilix based on configuration provided in web app

**About**
I will talk about Meilix how one can contribute to it. Benefits of the project Meilix Generator why it's not a regular distro 
if time allows I can even explain the code. the scripts for generating the Meilix

**Pre-requisites**

Bash for Meilix 

Python for Meilix Generator
- _Required setups_
python and flask installed for Meilix generator

**Expected duration**

_Time that your talk/workshop would take_
Around 30 min

**Level**

_Beginner_

**Resources**

_Add links to resources which can further be used to read up on the topic_
http://github.com/xeon-zolt/meilix/
http://github.com/xeon-zolt/meilix-generator/
http://blog.fossasia.org/author/xeon-zolt/

**Speaker Bio**

_Write a brief description about you here_
I am Harsh Lathwal final year student at North Cap University. I love using Linux and this was my GSoC 2017 project

###### - Can be done after the talk/workshop -

[slides](https://prezi.com/view/nrrOf3KZE3AQ1kTR0Ivu/)

[Include link to video here](link)

**Comment by rajudev** [comment]
Correct me If I am wrong. 
You mention `Meilix is the only LXQT based distro in the market` 
Isn't the claim wrong?

**Comment by xeon-zolt** [comment]
you are partially correct actually other distributions also offer LXQT but not as primary desktop like manjaro is available with LXQT but default Manjaro is with XFCE. Ubuntu is still coming up with LXDE which was created by my mentor but no LXQT official version

**Comment by hellozee** [comment]
Doesn't SUSE Studio do the same thing?

**Comment by shivan1b** [comment]
Hi, @xeon-zolt! Could you please tell if you'd be available this Sunday (18 March 2018) for this talk?

**Comment by xeon-zolt** [comment]
Yup
