### ISSUE TITLE
Women and minorities in Technology | My take on our cultural influences and the diversity crisis. 

### ISSUE THREAD

**Issue by rajudev** [linuxchixin/talks#26]
**Abstract**

A talk on the lack of diversity of minorities and Women in the Technology scenario of companies and organizations today. 
**About**
You might have already heard or experienced the of the lack of diversity of Women in Technology. You might have already heard about attempts by a few organizations for balancing the diversity issue following there own approaches to solve the problem. Well, I will be mentioning these efforts but this won't be the usual ' Diversity in Technology Talk'. 
This talk would be my attempt to present the past/present of the diversity scenario in technology following my own point of view and experiences around them.

 

**Pre-requisites**
none

**Expected duration**
1 hour

**Level**

Any

**Resources**

1. [Mozilla's Statement on Diversity ](https://blog.mozilla.org/press/2014/03/mozilla-statement-on-diversity/)
2. [Gnome needs women contributors ](https://www.linux.com/news/gnome-needs-women)
3. [KDE Women ](https://community.kde.org/KDE_Women)
4. [Debian Women ](https://www.debian.org/women/about)
more resoursces will be added in the meanwhile. 

**Speaker Bio**
I am Raju Devidas. Just another free software enthusiast.
I contribute to many free software projects in many different ways like code, package management, documentation, publicity and stuff.  
Feel free to talk to me regarding my interests which include Robotics, Free software/hardware, web technologies, software package management and stuff. 
I also have a [blog](http://rajudev.gitlab.io/) , but its not much updated.

**Comment by rajudev** [comment]
Note to meetup organizers:
Please let me know here beforehand while finalizing this talk. 
Preparation for this talk is a work in progress and I will need some time to get it done. Although feel free to ask me about the progress and preparations on this issue.

**Comment by cocoa1231** [comment]
Hey. Would you be available to give this talk on 24th?

**Comment by rajudev** [comment]
I am closing this issue for now, not getting enough time for preparing the content. Will open the issue once I am ready for it.
