### ISSUE TITLE
Competitive Programming and other war related stuff

### ISSUE THREAD

**Issue by lbsrex** [linuxchixin/talks#29]
An introductory talk about how to get started with competitive programming.

Provision of various resources. 

And maybe a few example questions broken down into steps to a complete solution.

**Comment by shivan1b** [comment]
@lbsrex Do you have any slides/helpful docs relating to your talk? Please update here.

**Comment by lbsrex** [comment]
@shivan1b, Cool.

**Comment by shivan1b** [comment]
@lbsrex ping. Could you please update the slides/other resources here?

**Comment by lbsrex** [comment]
Sorry!!! It totally slipped from my mind. I'll do it today itself.
