### ISSUE TITLE
Understanding .git

### ISSUE THREAD

**Issue by shivan1b** [linuxchixin/talks#30]
**Abstract**

What is the mysterious `.git`

**About**

 A small exploration of `.git` and why it is there.

**Pre-requisites**

- Have git pre-installed

**Expected duration**

30 mins

**Level**

Beginner - Intermediate

**Resources**

https://stackoverflow.com/questions/29217859/what-is-the-git-folder/29220296
https://git-scm.com/docs/gitrepository-layout
https://medium.freecodecamp.org/understanding-git-for-real-by-exploring-the-git-directory-1e079c15b807

**Speaker Bio**

Developer who does not need caffeine. Currently works with Django. Linux and mathematics are love. This does not mean she knows everything about them.

**Comment by vipulgupta2048** [comment]
Is this open for someone to take or is @shivan1b taking it? 
I would love to explore more into git by going deeper into .git

**Comment by shivan1b** [comment]
Hey @vipulgupta2048!
I am going to take it, not in the next meetup though. If you'd like to take it up, no problem there. Go ahead. :+1:

**Comment by RaiVaibhav** [comment]
Wating for this talk in next Pycon. :)

**Comment by vipulgupta2048** [comment]
Hi, this talk is scheduled for the next meetup, you can check here [1] and RSVP, also bring the girls that you think would be interested for the same. We are always looking forward to seeing more female participation.

[1] -https://www.meetup.com/LinuxChix-India-Meetup/events/mlddmnyxhbbc/

**Comment by vipulgupta2048** [comment]
Ps. PyCon is entirely something else that relates to Python.

**Comment by RaiVaibhav** [comment]
Hey Vipul,
Thanks for information I will try my best to aware my colleague to attend the Meetup.
I am not saying that shift it to PyCon, I thought this talk will be in PyCon, I didn't know that it already scheduled.
Also I think when we say PyCon it doesn't entirely means `Python` :)
