### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by garvitdelhi** [linuxchixin/talks#31]
**Abstract**

Want to have the same environment for all the developers? Let's discuss docker and how it solves the problem. 

**About**

I will be talking about what is docker and how docker solves the “Works On My Machine” problem. I will try to answer the following questions: How to create your own dockerized environment? How to deploy them on production servers? What is docker-compose? If time permits I will also touch a little bit about Kubernetes, a system to manage the deployment of multiple containers. 

**Pre-requisites**

Have *nix system on their laptops.

**Expected duration**

1 hour

**Level**

Intermediate

**Resources**

_Add links to resources which can further be used to read up on the topic_
https://docs.google.com/presentation/d/1RQW3xSaoBM1N4Md3y1aEZyzz4XgreOmXrngBm81XuEo/edit#slide=id.g3bccdabfb9_1_241
https://docs.docker.com/

**Speaker Bio**

[Garvit Khatri](https://garvit.in/about/)

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by shivan1b** [comment]
Hi, Garvit!
Will you be available for this talk this Sunday?

**Comment by shivan1b** [comment]
Hi, Garvit!
Will you be available for this talk this Sunday i.e. 10 June?

**Comment by garvitdelhi** [comment]
Hi, @shivan1b sure I would like to give it on 10th of this week.

**Comment by shivan1b** [comment]
Awesome. Confirming your talk for this meetup then! :smile:
