### ISSUE TITLE
Why should you contribute to Open Source?

### ISSUE THREAD

**Issue by CuriousLearner** [linuxchixin/talks#32]
**Abstract**

Just a simple discussion on [Why should you contribute to Open Source?](https://medium.com/@CuriousLearner/why-you-should-contribute-to-open-source-70e6f4a73ae1)

Would try to answer things like "What's in it for me?"

**Pre-requisites**

 - Willingness to learn with a lots of questions

 _Required setups_
None

**Expected duration**
30 mins

**Level**
Beginner

**Resources**

Shall be up soon.

**Speaker Bio**

A random guy trying to contribute to Open Source.

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by cocoa1231** [comment]
Hi

Would you be available to give this talk on the 24th?

**Comment by CuriousLearner** [comment]
Nope @cocoa1231

**Comment by cocoa1231** [comment]
Hey!

Are you available to give this talk on the 5th Aug. Meetup?

**Comment by CuriousLearner** [comment]
Hello,

I think this one was delivered earlier in LinuxChix meetup.
