### ISSUE TITLE
Handson on Debian packaging of nodejs modules.

### ISSUE THREAD

**Issue by Manas-kashyap** [linuxchixin/talks#33]
It will be a Hands-on to pack some small modules of nodejs for Debian (Basicallly npm modules), I will also cover some tools like npm2deb and other tools like lintian , and fixing some patches using Quilt .

Expected Duration
1hr to 1:30 hr

Track
LinuxChix talks are divided intro three tracks:
- Beginner

Pre-requisite
Laptop with Debian sid in the docker.
good internet connection.

[Debian_packaging.pdf](https://github.com/linuxchixin/talks/files/1691623/Debian_packaging.pdf)

**Comment by anubhakushwaha** [comment]
@CuriousLearner Where will this session be given?

**Comment by CuriousLearner** [comment]
@anubhakushwaha The venue is not finalized yet. It would be most probably on the next coming meetup on 18th Feb.

It should be announced soon.

**Comment by Manas-kashyap** [comment]
@anubhakushwaha the session is in next meetup, https://www.meetup.com/LinuxChix-India-Meetup/events/244635502/
