### ISSUE TITLE
Introduction to Embedded system development

### ISSUE THREAD

**Issue by kuldeepdhaka** [linuxchixin/talks#34]
**Abstract**

Introduction to Embedded system development

**About**

Introduction to embedded system, is primarily targeted at people who want to design electronics.
Talk will include development using FLOSS tools and libraries.
Talk will comprise of personal experiences, how to start building things and technical details.
Talk might include a demo of programming and runing code on a microcontroller.
Talk might include personal insight on IOT and electronics industry.

**Pre-requisites**

- **Curiosity** (**Most important!** Other things are just for reference)

###### Things that would be using or talking about
- Coding in C
- Cross Compiling and Compiler (ARM GCC)
- Build system (Makefile)
- PCB Design (KiCAD)
- Microcontroller (ARM Cortex M)
- Library for ARM Microcontroller (UniCore-MX)
- Flashing and debugging tool (GDB, OpenOCD)
- GNU/Linux Flavour (Arch Linux - Not directly but may give some instruction and experience)

- HDMI/VGA projector (for presentation)

Note: I might be doing demo but there is no special requirement. (Just mentioning for reference)

**Expected duration**

1hr or something.

**Level**

Beginners

**Resources**

UniCore-MX: A vendor agnostic, community maintained, FLOSS library for ARM Cortex Microcontroller
https://github.com/insane-adding-machines/unicore-mx

https://en.wikipedia.org/wiki/Embedded_system
https://en.wikipedia.org/wiki/Microcontroller
https://en.wikipedia.org/wiki/Cross_compiler
https://en.wikipedia.org/wiki/KiCad
https://en.wikipedia.org/wiki/GNU_make
https://en.wikipedia.org/wiki/STM32

**Speaker Bio**

Kuldeep is the co-founder of [Mad Resistor](https://madresistor.com).
He is the co-creator of [Box0](https://madresistor.com/box0) project and [diy-VT100](https://madresistor.com/diy-vt100) which are loved by FLOSS community worldwide.
He is also a core-contributor and USB maintainer of UniCore-MX.
Apart from that, he explores other fields, help animals and support equality.

[Twitter: \@kuldeepdhaka9](https://twitter.com/kuldeepdhaka9)
[Github: kuldeepdhaka](https://github.com/kuldeepdhaka)

###### - Can be done after the talk/workshop -

[intro-emb-sys-linuxchix.pdf](https://github.com/linuxchixin/talks/files/1913861/intro-emb-sys-linuxchix.pdf) _Minor corrections_
[intro-emb-sys-linuxchix.pdf](https://github.com/linuxchixin/talks/files/1913845/intro-emb-sys-linuxchix.pdf) _Original_

[Include link to video here](link)

**Comment by shivan1b** [comment]
Hi, Kuldeep!
Will you be available for your talk this Sunday?

**Comment by kuldeepdhaka** [comment]
Hey Shivani
Yes, I'm available.

**Comment by shivan1b** [comment]
Awesome! Thanks, Kuldeep.
Confirming your talk for this meetup. Will update you about the venue and timings soon.
