### ISSUE TITLE
Build and Deploy your applications in minutes with Hasura

### ISSUE THREAD

**Issue by parulagg27** [linuxchixin/talks#39]
**Abstract**
We’ll discuss about Hasura platform, how to get started with it and what are the different ways in which Hasura can help ( hence, the reasons why anyone should use Hasura). This will be followed by a hands on session on how to use Hasura services to make your project. The talk will also include a project demo.

**About**
Hasura provides Platform as a service(PaaS) with Backend as a service components(BaaS). It gives you everything you need for your backend including built-in APIs for data, auth and filestore backed by Postgres and build it up in minutes with no hassle! 
It also provides community contributed starter projects for your app on [hasura hub](https://hasura.io/hub), ranging from a working slack bot to a sample e-commerce schema, that you can extend and modify accordingly. 
It also helps you deploy your custom code in any language on the server with just a ‘git push’ (APIs, webapps, static-files). Moreover, It allows you to add multiple clusters to a single project, so you can manage multiple environments (dev, staging, production, etc.) easily. 

**Pre-requisites**
* Basics of CLI
* Hasura CLI installed. Instructions for installing the same can be found [here](https://docs.hasura.io/0.15/manual/install-hasura-cli.html).
*Update*: Basics of Git

**Expected duration**
45-50 min

**Level**
Beginner to Intermediate

**Resources**
1. https://docs.hasura.io/0.15/manual/getting-started/index.html
2. https://www.youtube.com/channel/UCZo1ciR8pZvdD3Wxp9aSNhQ
3. https://blog.hasura.io/what-is-hasura-ce3b5c6e80e8

**Speakers Bio**
We are [Parul Aggarwal](https://github.com/parulagg27) and [Aishna Gupta](https://github.com/aishna2502) with different years of experiences and sharing common interests and beliefs of helping others explore the world beyond! :)

Parul is a second year undergraduate and a web developer. She is an open source enthusiast and loves programming in python. Currently, she is Web Development head at Developers Student Club, BVP (formerly, GDG-BVP) and one of the organizing team members of Mozilla Open Source Club, BVP. 
Aishna is a graduate from IGDTUW and has been placed in Oracle India, Bangalore. She is an ML enthusiast and has won many hackathons, including Smart India Hackathon( 2017 - First Prize winner, 2018 - Runner Up). Currently, she is one of the organizing team members of WTM, New Delhi. 
**Twitter Handles**: Parul - [@parulagg27](https://twitter.com/parulagg27), Aishna - [@GuptaAishna](https://twitter.com/GuptaAishna)

cc: @vipulgupta2048

**Link to the slides** 
[Here](https://docs.google.com/presentation/d/1zaE6LpXCyFKq7rXbDqVAWULvo_yj9XVwM89WlhAfIsk/edit?usp=sharing)

**Comment by parulagg27** [comment]
Yeah, sure! We both are available that day.

**Comment by cocoa1231** [comment]
Yes! Great! So confirming your talk :)

Thank you :)

**Comment by parulagg27** [comment]
Sure @cocoa1231 😄
