### ISSUE TITLE
Maintaining projects that depends on other multiple open source projects

### ISSUE THREAD

**Issue by iayanpahwa** [linuxchixin/talks#43]
**Abstract**

Often we pull open source libraries in our project which are maintained in different manner , most of them using git based version control system, so we end up having dependencies. Your project depends on a library which depends on other library and so on. So how to maintain such project, attendees will learn in this talk. 

**About**

Maintaining open source projects and track dependency changes.

**Pre-requisites**

* Basic understanding of git

* Have git installed on workstation 

**Expected duration**

30 minutes

**Level**

Intermediate 

**Resources**

https://www.youtube.com/watch?v=a_Ua0I9KVwY

**Speaker Bio**

Just a tech: codeNsolder.com/about

###### - Can be done after the talk/workshop -

[Video](https://www.youtube.com/watch?v=a_Ua0I9KVwY)
[Blog](https://iayanpahwa.github.io/Managing-Dependencies-with-Git-and-bonus-advance-concepts/)

**Comment by sakshisangwan** [comment]
Hey, are you available to deliver this talk on the upcoming meetup i.e. 22nd July? :D

**Comment by iayanpahwa** [comment]
Yes!

**Comment by iayanpahwa** [comment]
@sakshisangwan added resources. Good to close the issue now.
