### ISSUE TITLE
Bot Creation Bootcamp (BCB) 

### ISSUE THREAD

**Issue by vipulgupta2048** [linuxchixin/talks#46]
Adding a skeletal issue for people to understand. If approved, please, someone, expand on it or edit it however you wish.

**Abstract**
Making bots is a great skill that is both easy and fun to learn. 
People are often anxious about starting with bots, even though there is almost always good documentation or tutorials available for many platforms in several languages. 
Bot Conf or BCB will be the ultimate bot developing workshop to kickstart people who are interested to learn, try and play with bots of different kinds for different platforms.  
Making bots from scratch is easy but very time-consuming. Hence BCB is all about teaching people how to start with it and later let them innovate in their own time, with the help of other people. 

**Speakers**
@realslimshanky could cover Telegram bots 
@vipulgupta2048 volunteers for Twitter bots made for PyCon India.

Other prospective platforms 
- ChatBots on websites
- IRC bots (like Batul in DGplug, or meeting-bot by Debian), 
- Using Dialogflow, or maybe even Google Actions or Alexa Skills (But takes too long), 
- GitHub, Discord, Slack.   

**About**
I am a student pursuing Computer Science Engg., and likes Python, Linux, OSS, vanilla and the comic Calvin and Hobbes. I like to close issues on GitHub in my free time. 

**Pre-requisites**
Prerequisites would be related to the programming language used by the workshop taker. But since it's just starting out, there won't be much issues. Also, popular bots support most languages. 
Example - I would be using Python for Twitter bots, but Twitter bots are made in Java as well.

**Expected duration**
4-5 hours total
30 minutes each --> 2-3 workshops
After that, _build what you like_ event. Like a controlled devsprint. Where workshop takers become mentors and attendees become either contributors or make their own bots on any other ideas they have. Good ones can get rewarded with stickers or other swag. 

**Level**
Beginner/Intermediate

**Comment by utkarsh2102** [comment]
Hi,
Are you guys free to take this session on 2nd September?

**Comment by realslimshanky** [comment]
@utkarsh2102 Yes, I confirm my presence for the day.

**Comment by vipulgupta2048** [comment]
@utkarsh2102 Will be there.

**Comment by utkarsh2102** [comment]
Awesome!
Scheduling the talk then.

**Comment by vipulgupta2048** [comment]
Slides. 
- Twitter Bots - https://slides.com/vipulgupta2048/2itterbots/
- Telegram bots - https://slides.com/realslimshanky/tbotpython
