### ISSUE TITLE
Android development 101

### ISSUE THREAD

**Issue by AniVerma17** [linuxchixin/talks#48]
**Abstract**

Talk on Android app development for beginner level.

**About**

This talk would cover the basics of Android app development. Starting from a brief on the basic components of an Android application, we would create a sample app to demonstrate the various aspects of developing an Android app.

**Pre-requisites**

- **Required skills:** Understanding of Java/Kotlin and XML.

- **Required setups:** Android Studio IDE installed. You can download it from [here](https://developer.android.com/studio/).

**Expected duration**

1 hour

**Level**

Beginner

**Resources**

- [Developers Guide | Android Developers](https://developer.android.com/guide/)

**Speaker Bio**

[Animesh Verma](https://github.com/AniVerma17)
Fourth year CSE undergrad at Amity University; full-stack web and app developer.

###### - Can be done after the talk/workshop -
[Slides](https://docs.google.com/presentation/d/14jwQCMKQyDTt-AQwVX1xek4QAbJwLezIgfPRC-otCxY/edit?usp=sharing)

**Comment by cocoa1231** [comment]
Confirming this talk for September 30 Meetup

**Comment by AniVerma17** [comment]
Alright. :+1:
