### ISSUE TITLE
Shell Scripting 101

### ISSUE THREAD

**Issue by ajyotirmay** [linuxchixin/talks#50]
**Abstract**

Talk on Shell Scripting for beginners

**About**

This talk will cover a brief introduction to Shell Scripting. And will answer the following questions:
- What is Shell?
- How to work in a shell?
- Why to write scripts?
- How to write a script?

**Pre-requisites**

- Basic knowledge of command line/terminal

- A Linux distro (anyone would work)

**Expected duration**

30 minutes

**Level**

_Beginner_

**Resources**

[Linux Shell Scripting Tutorial](https://bash.cyberciti.biz/guide/Main_Page)

**Speaker Bio**

[Apurv Jyotirmay](http://github.com/ajyotirmay/)
Computer Science graduate, with interests in Linux, application development (mobile/desktop) and full stack web development.

**Comment by nihilist-banana** [comment]
Are you available to give this talk in the upcoming meetup on the 12th of May?

**Comment by ajyotirmay** [comment]
@nihilist-banana This talk was already covered in one of the meetups. Do you want me to do it again?

**Comment by shivan1b** [comment]
@ajyotirmay thanks for informing. COuld you please add this talk to README then?

**Comment by shivan1b** [comment]
Thanks for contributing to LinuxChix India with your talk. :)
