### ISSUE TITLE
Post Office Protocol and IMAP

### ISSUE THREAD

**Issue by Ishaan28malik** [linuxchixin/talks#54]
**Abstract**

_So the talk is about the difference between open source mailing system like Zimbra and Thunderbird and the Gmail  _

**About**

_So it's about POP and IMAP and  it will be a short discriptive talk with a little examples how they both differ_

**Pre-requisites**

Just a basic understanding what a protocol is and what an e-mail is

**Expected duration**

_20 minutes approx_

**Level**

_Beginner_

**Resources**

_Add links to resources which can further be used to read up on the topic_

**Speaker Bio**

_Hey my name is Ishaan Malik i am a junior undergrad student , I am passionately fond of pure and Applied Mathematics and IOT. I contribute in Open Source and special interest in research , I love Python and contributing to Open Source _

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[ link to video is here](https://youtu.be/OAvn4k95tVs)

**Comment by CuriousLearner** [comment]
@Ishaan28malik Can you please add the description for your talk?

**Comment by Ishaan28malik** [comment]
Yes @CuriousLearner on my way

**Comment by Ishaan28malik** [comment]
@CuriousLearner done please check and I am free on 9th November  .

**Comment by utkarsh2102** [comment]
So can I confirm your talk for 9th November?

**Comment by Ishaan28malik** [comment]
Yup

**Comment by utkarsh2102** [comment]
Alright.
D'you need anything from our end?

**Comment by Ishaan28malik** [comment]
@utkarsh2102  no nothing  thanks  ...

**Comment by utkarsh2102** [comment]
Alright.
@CuriousLearner, please add the appropriate labels. This is scheduled for 9th November.

**Comment by Ishaan28malik** [comment]
Added link to the video
