### ISSUE TITLE
Assembly 101

### ISSUE THREAD

**Issue by nk521** [linuxchixin/talks#57]
**Abstract**

I'll cover some basic concepts of memory, arch, and heap

**Pre-requisites**

- _Required skills_
C basics, data types and loops/if-else
- _Required setups_
Come with a linux or windows+WSL or mac system.

**Expected duration**

0045-0060

**Level**

_Beginner_

**Speaker Bio**

_I'm Nikhil Kumar Singh. I just study and research on random things. :D_

###### - Can be done after the talk/workshop -

https://nk521.github.io/asm/

https://www.github.com/nk521/asm

**Comment by cocoa1231** [comment]
Hey @nk521 
Can I confirm this for December 9?

**Comment by nk521** [comment]
Yep!

**Comment by cocoa1231** [comment]
Awesome! Allons-y!

**Comment by dufferzafar** [comment]
This too is awaiting slides / video!
