### ISSUE TITLE
D for Django

### ISSUE THREAD

**Issue by pythongiant** [linuxchixin/talks#60]
**Abstract**
Building web-apps in Django.
**About**

Topics covered 
- Basics of Django programming
- Basic Server side programming in python

**Pre-requisites**

- __Basics of Python__
- __A working unix system__

**Expected duration**

_45 mins_

**Level**

_Beginner_

**Resources**
_https://www.djangoproject.com/_

**Speaker Bio**

_10th grader that likes to code_

###### - Can be done after the talk/workshop -

[Include link to slides here](https://docs.google.com/presentation/d/1qvICLK7O4qdIRkABQjEZzz-mD3wqLZYSY3FAynjiZkw/edit?usp=sharing)
[Include link to video here](link)

**Comment by CuriousLearner** [comment]
Hey @pythongiant,

Can you please add some slides you'd like to present?

**Comment by pythongiant** [comment]
@CuriousLearner check it out now

**Comment by pythongiant** [comment]
@CuriousLearner making a Issue in PyDelhi since that seems like a more relevant community for this
