### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by utkarsh2102** [linuxchixin/talks#61]
There's no record of 2018's talks.
The `README.md` is to be updated for the same.

**Comment by pythongiant** [comment]
um are logs of 2018 mentioned

**Comment by pythongiant** [comment]
If yes, I'll do it.

**Comment by utkarsh2102** [comment]
@pythongiant, there are talk issues that are closed.
You can refer to them. Would take not more than 30-45 minutes, probably.

**Comment by utkarsh2102** [comment]
There are not more than 12-13 issues.

**Comment by pythongiant** [comment]
Hey @utkarsh2102 I have been looking at a few issues but there are many issues where there is no indication weather or not those talks have been given or not

**Comment by CuriousLearner** [comment]
This should've or still should be done before closing the issues once the talk is done.

It takes just 2 minutes, but now would take at least 2-3 hours to cross-verify and update everything.

Just my 2 paise!

**Comment by shivan1b** [comment]
You're right. @pythongiant if you can collect the already closed issues and add them to README, it';ll be great. Let's make this a habit to ask speakers to add their own names to the list.

**Comment by pythongiant** [comment]
Alright. Will make a PR by tonight
