### ISSUE TITLE
Go or Not to Go(from java-script developer perspective)?

### ISSUE THREAD

**Issue by RN0311** [linuxchixin/talks#64]
**Abstract**
Go’s excellent tooling, elegant concurrency model and unique approach to object-orientation have captivated the attention of developers from compiled and scripting languages alike. Through this talk, I want the audience to ponder on what "the server language of future"provided by drawing comparison within the two languages.

**About**

I'll dive the audience from absolute base level to the prowess of GoLang by citing examples in GoLang and in java-script both. To top it off, will add more resources to help people get started.

**Pre-requisites**

* Knowledge of basic GoLang syntax.

**Required setups**

* Go 1.11 

**Expected duration**

* 30 minutes

**Level**

* Beginner 

**Resources**

* [Why Go](https://nathany.com/why-go/)
* [Two Go Developers Who Switched from JavaScript and Ruby](https://thenewstack.io/two-go-developers-switched-javascript-ruby/)

**Speaker Bio**

Founder of WomenWhoGo, Delhi chapter.

**Comment by nihilist-banana** [comment]
Hey, are you available to give this talk in the meetup on 12th?

**Comment by RN0311** [comment]
Hey!
I would love to, but won't be available on 12th. Post that, we're organizing a combined meet up with LinuxChix + PyLadies + WomenWhoGo, Delhi - on 25th May, there I might take up this topic.
