### ISSUE TITLE
Cryptography - What it is all about?

### ISSUE THREAD

**Issue by The-Lady** [linuxchixin/talks#72]
**About**

_**Cryptography** is present since ancient times yet very few people know about it. With this talk, I would like to showcase a very **ancient** and **cryptic** field which has not died but in fact has been reborn in **recent** times and is present in our daily lives more than we might think._

**Pre-requisites**

- _Required skills_   
   _None_

- _Required setups_  
   _None_

**Expected duration**  

_30 minutes_

**Level**

_Beginner_

**Resources**

[Cryptography Introduction as per Wikipedia](https://en.wikipedia.org/wiki/Cryptography)
[Cryptography Introduction as per GeeksForGeeks](https://www.geeksforgeeks.org/cryptography-introduction-to-crypto-terminologies/)
[A Comprehensive Guide For Cryptography By Dan Boneh and Victor Shoup](https://drive.google.com/open?id=1gIZfCRFCuaSWH2QZKU-7-h5Rg0wMBrRE)

**Speaker Bio**

_Final year Engineering student and a cyber security enthusiast_

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by cocoa1231** [comment]
Hey @The-Lady,
Would you be available to give this talk on Feb. 17?

**Comment by The-Lady** [comment]
Hi @cocoa1231,
Yes I am available.

**Comment by shivan1b** [comment]
Hi @The-Lady ! Could you please add your talk to the README section of this repo?

**Comment by shivan1b** [comment]
Thanks for contributing to LinuxChix India with your talk. :)
